// Mocks generated by Mockito 5.4.6 from annotations
// in audiovault/test/services/audio_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:audiovault/services/position_service.dart' as _i2;
import 'package:audiovault/services/preferences_service.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PositionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPositionService extends _i1.Mock implements _i2.PositionService {
  MockPositionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> savePosition({
    required String? bookPath,
    required int? chapterIndex,
    required Duration? position,
    required int? globalPositionMs,
    required int? totalDurationMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePosition,
          [],
          {
            #bookPath: bookPath,
            #chapterIndex: chapterIndex,
            #position: position,
            #globalPositionMs: globalPositionMs,
            #totalDurationMs: totalDurationMs,
          },
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<({int chapterIndex, Duration position})?> getPosition(
          String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [bookPath],
        ),
        returnValue:
            _i3.Future<({int chapterIndex, Duration position})?>.value(),
      ) as _i3.Future<({int chapterIndex, Duration position})?>);

  @override
  _i3.Future<String?> getLastPlayedBookPath() => (super.noSuchMethod(
        Invocation.method(
          #getLastPlayedBookPath,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<
      List<
          ({
            String bookPath,
            int globalPositionMs,
            int totalDurationMs,
            int updatedAt
          })>> getAllPositions() => (super.noSuchMethod(
        Invocation.method(
          #getAllPositions,
          [],
        ),
        returnValue: _i3.Future<
            List<
                ({
                  String bookPath,
                  int globalPositionMs,
                  int totalDurationMs,
                  int updatedAt
                })>>.value(<({
          String bookPath,
          int globalPositionMs,
          int totalDurationMs,
          int updatedAt
        })>[]),
      ) as _i3.Future<
          List<
              ({
                String bookPath,
                int globalPositionMs,
                int totalDurationMs,
                int updatedAt
              })>>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i4.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> getLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #getLibraryPath,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setLibraryPath(String? path) => (super.noSuchMethod(
        Invocation.method(
          #setLibraryPath,
          [path],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> clearLibraryPath() => (super.noSuchMethod(
        Invocation.method(
          #clearLibraryPath,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool?> getAnalyticsConsent() => (super.noSuchMethod(
        Invocation.method(
          #getAnalyticsConsent,
          [],
        ),
        returnValue: _i3.Future<bool?>.value(),
      ) as _i3.Future<bool?>);

  @override
  _i3.Future<void> setAnalyticsConsent(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAnalyticsConsent,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setThemeMode(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getMetadataEnrichment() => (super.noSuchMethod(
        Invocation.method(
          #getMetadataEnrichment,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setMetadataEnrichment(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setMetadataEnrichment,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> getAutoRewind() => (super.noSuchMethod(
        Invocation.method(
          #getAutoRewind,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> setAutoRewind(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoRewind,
          [value],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> getSkipInterval() => (super.noSuchMethod(
        Invocation.method(
          #getSkipInterval,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> setSkipInterval(int? seconds) => (super.noSuchMethod(
        Invocation.method(
          #setSkipInterval,
          [seconds],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
