// Mocks generated by Mockito 5.4.6 from annotations
// in audiovault/test/screens/book_download_prompt_bug_exploration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:kowhai/models/audiobook.dart' as _i7;
import 'package:kowhai/models/bookmark.dart' as _i3;
import 'package:kowhai/services/drive_book_repository.dart' as _i8;
import 'package:kowhai/services/drive_download_manager.dart' as _i9;
import 'package:kowhai/services/drive_library_service.dart' as _i4;
import 'package:kowhai/services/position_service.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookmark_1 extends _i1.SmartFake implements _i3.Bookmark {
  _FakeBookmark_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DriveLibraryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveLibraryService extends _i1.Mock
    implements _i4.DriveLibraryService {
  MockDriveLibraryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<String> bookDir(
    String? folderId, {
    String? folderName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookDir,
          [folderId],
          {#folderName: folderName},
        ),
        returnValue: _i5.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #bookDir,
            [folderId],
            {#folderName: folderName},
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<Set<String>> driveBookDirs() => (super.noSuchMethod(
        Invocation.method(
          #driveBookDirs,
          [],
        ),
        returnValue: _i5.Future<Set<String>>.value(<String>{}),
      ) as _i5.Future<Set<String>>);

  @override
  _i5.Future<List<_i7.Audiobook>> loadDriveBooks() => (super.noSuchMethod(
        Invocation.method(
          #loadDriveBooks,
          [],
        ),
        returnValue: _i5.Future<List<_i7.Audiobook>>.value(<_i7.Audiobook>[]),
      ) as _i5.Future<List<_i7.Audiobook>>);

  @override
  _i5.Future<List<_i7.Audiobook>> rescanDrive(
          {void Function(String)? onProgress}) =>
      (super.noSuchMethod(
        Invocation.method(
          #rescanDrive,
          [],
          {#onProgress: onProgress},
        ),
        returnValue: _i5.Future<List<_i7.Audiobook>>.value(<_i7.Audiobook>[]),
      ) as _i5.Future<List<_i7.Audiobook>>);

  @override
  _i5.Future<void> removeUndownloadedBooks() => (super.noSuchMethod(
        Invocation.method(
          #removeUndownloadedBooks,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> onRootFolderChanged(String? newRootFolderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #onRootFolderChanged,
          [newRootFolderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> startDownload(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #startDownload,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.Audiobook?> promoteToLocal(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #promoteToLocal,
          [folderId],
        ),
        returnValue: _i5.Future<_i7.Audiobook?>.value(),
      ) as _i5.Future<_i7.Audiobook?>);

  @override
  _i5.Future<void> undownloadBook(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #undownloadBook,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> totalSizeBytes(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #totalSizeBytes,
          [folderId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> deleteLocalFiles(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLocalFiles,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DriveBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveBookRepository extends _i1.Mock
    implements _i8.DriveBookRepository {
  MockDriveBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> upsertDriveBook(_i8.DriveBookRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertDriveBook,
          [record],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> upsertFile(_i8.DriveFileRecord? record) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertFile,
          [record],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.DriveBookRecord>> getAllDriveBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllDriveBooks,
          [],
        ),
        returnValue: _i5.Future<List<_i8.DriveBookRecord>>.value(
            <_i8.DriveBookRecord>[]),
      ) as _i5.Future<List<_i8.DriveBookRecord>>);

  @override
  _i5.Future<_i8.DriveBookRecord?> getDriveBook(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDriveBook,
          [folderId],
        ),
        returnValue: _i5.Future<_i8.DriveBookRecord?>.value(),
      ) as _i5.Future<_i8.DriveBookRecord?>);

  @override
  _i5.Future<void> resetBookDownloads(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #resetBookDownloads,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteDriveBook(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDriveBook,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.DriveFileRecord>> getFilesForBook(String? folderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFilesForBook,
          [folderId],
        ),
        returnValue: _i5.Future<List<_i8.DriveFileRecord>>.value(
            <_i8.DriveFileRecord>[]),
      ) as _i5.Future<List<_i8.DriveFileRecord>>);

  @override
  _i5.Future<void> updateFileState(
    String? folderId,
    int? fileIndex,
    _i8.DriveDownloadState? state, {
    String? localPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFileState,
          [
            folderId,
            fileIndex,
            state,
          ],
          {#localPath: localPath},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> resetStaleDownloads() => (super.noSuchMethod(
        Invocation.method(
          #resetStaleDownloads,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAsDownloaded(
    String? folderId,
    bool? downloaded,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsDownloaded,
          [
            folderId,
            downloaded,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<Set<String>> getRemoteOnlyFolderIds() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteOnlyFolderIds,
          [],
        ),
        returnValue: _i5.Future<Set<String>>.value(<String>{}),
      ) as _i5.Future<Set<String>>);

  @override
  _i5.Future<List<String>> findStaleFolderIds(Set<String>? scannedFolderIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #findStaleFolderIds,
          [scannedFolderIds],
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);
}

/// A class which mocks [DriveDownloadManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockDriveDownloadManager extends _i1.Mock
    implements _i9.DriveDownloadManager {
  MockDriveDownloadManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<_i9.DriveDownloadEvent> get downloadEvents => (super.noSuchMethod(
        Invocation.getter(#downloadEvents),
        returnValue: _i5.Stream<_i9.DriveDownloadEvent>.empty(),
      ) as _i5.Stream<_i9.DriveDownloadEvent>);

  @override
  _i5.Future<void> enqueueNextFiles({
    required String? folderId,
    required int? fromFileIndex,
    int? count = 3,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueNextFiles,
          [],
          {
            #folderId: folderId,
            #fromFileIndex: fromFileIndex,
            #count: count,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> enqueueAllFiles(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #enqueueAllFiles,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> cancelDownload(String? folderId) => (super.noSuchMethod(
        Invocation.method(
          #cancelDownload,
          [folderId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> downloadCover({
    required String? folderId,
    required String? coverFileId,
    required String? destDir,
    String? fileName = 'cover.jpg',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadCover,
          [],
          {
            #folderId: folderId,
            #coverFileId: coverFileId,
            #destDir: destDir,
            #fileName: fileName,
          },
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [PositionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPositionService extends _i1.Mock implements _i10.PositionService {
  MockPositionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> get databaseForTesting => (super.noSuchMethod(
        Invocation.getter(#databaseForTesting),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#databaseForTesting),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<_i2.Database> get sharedDb => (super.noSuchMethod(
        Invocation.getter(#sharedDb),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#sharedDb),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<void> savePosition({
    required String? bookPath,
    required int? chapterIndex,
    required Duration? position,
    required int? globalPositionMs,
    required int? totalDurationMs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePosition,
          [],
          {
            #bookPath: bookPath,
            #chapterIndex: chapterIndex,
            #position: position,
            #globalPositionMs: globalPositionMs,
            #totalDurationMs: totalDurationMs,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<({int chapterIndex, Duration position})?> getPosition(
          String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [bookPath],
        ),
        returnValue:
            _i5.Future<({int chapterIndex, Duration position})?>.value(),
      ) as _i5.Future<({int chapterIndex, Duration position})?>);

  @override
  _i5.Future<void> setBookStatus(
    String? bookPath,
    _i7.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateBookStatus(
    String? bookPath,
    _i7.BookStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookStatus,
          [
            bookPath,
            status,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i7.BookStatus> getBookStatus(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookStatus,
          [bookPath],
        ),
        returnValue:
            _i5.Future<_i7.BookStatus>.value(_i7.BookStatus.notStarted),
      ) as _i5.Future<_i7.BookStatus>);

  @override
  _i5.Future<Map<String, _i7.BookStatus>> getAllStatuses() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllStatuses,
          [],
        ),
        returnValue: _i5.Future<Map<String, _i7.BookStatus>>.value(
            <String, _i7.BookStatus>{}),
      ) as _i5.Future<Map<String, _i7.BookStatus>>);

  @override
  _i5.Future<_i3.Bookmark> addBookmark(_i3.Bookmark? bookmark) =>
      (super.noSuchMethod(
        Invocation.method(
          #addBookmark,
          [bookmark],
        ),
        returnValue: _i5.Future<_i3.Bookmark>.value(_FakeBookmark_1(
          this,
          Invocation.method(
            #addBookmark,
            [bookmark],
          ),
        )),
      ) as _i5.Future<_i3.Bookmark>);

  @override
  _i5.Future<List<_i3.Bookmark>> getBookmarks(String? bookPath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookmarks,
          [bookPath],
        ),
        returnValue: _i5.Future<List<_i3.Bookmark>>.value(<_i3.Bookmark>[]),
      ) as _i5.Future<List<_i3.Bookmark>>);

  @override
  _i5.Future<void> deleteBookmark(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteBookmark,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateBookmark(
    int? id, {
    required String? label,
    String? notes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookmark,
          [id],
          {
            #label: label,
            #notes: notes,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> getLastPlayedBookPath() => (super.noSuchMethod(
        Invocation.method(
          #getLastPlayedBookPath,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<
      List<
          ({
            String bookPath,
            int globalPositionMs,
            int totalDurationMs,
            int updatedAt
          })>> getAllPositions() => (super.noSuchMethod(
        Invocation.method(
          #getAllPositions,
          [],
        ),
        returnValue: _i5.Future<
            List<
                ({
                  String bookPath,
                  int globalPositionMs,
                  int totalDurationMs,
                  int updatedAt
                })>>.value(<({
          String bookPath,
          int globalPositionMs,
          int totalDurationMs,
          int updatedAt
        })>[]),
      ) as _i5.Future<
          List<
              ({
                String bookPath,
                int globalPositionMs,
                int totalDurationMs,
                int updatedAt
              })>>);
}
